# ------------------------------------------------------------------------------
# SecretProviderClass
#
# Retrieves the Amazon RDS credentials stored in AWS Secrets Manager
# using Amazon EKS Pod Identity.
#
# The Secrets Store CSI Driver synchronizes the credentials into
# a Kubernetes Secret consumed by the Orders microservice.
# ------------------------------------------------------------------------------
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.secretProviderClass }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secrets.awsRegion }}
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.secrets.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  # store the retrieved secrets in a Kubernetes Secret and make them available to the Orders microservice
  secretObjects:
    - secretName: {{ .Values.app.persistence.secret.name }}
      type: Opaque
      data:
        - objectName: username
          key: RETAIL_ORDERS_PERSISTENCE_USERNAME
        - objectName: password
          key: RETAIL_ORDERS_PERSISTENCE_PASSWORD