# ============================================================================
# UI SERVICE - CUSTOM VALUES 
# ============================================================================
 
# ----------------------------------------------------------------------------
# IMAGE CONFIGURATION
# ----------------------------------------------------------------------------
replicaCount: 1

image:
  repository: tcollins520/retail-store-catalog
  pullPolicy: IfNotPresent
  tag: "1.3.0"

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  name: catalog
  targetPort: 8080

serviceAccount:
  create: true
  name: catalog


# ----------------------------------------------------------------------------
# SECURITY
# ----------------------------------------------------------------------------
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

  seccompProfile:
    type: RuntimeDefault

  capabilities:
    drop:
      - ALL
podSecurityContext:
  fsGroup: 1000

# ----------------------------------------------------------------------------
# HEALTH PROBES
# ----------------------------------------------------------------------------
probes:
  startup:
    path: /health

  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5

  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
# ----------------------------------------------------------------------------
# RESOURCE MANAGEMENT
# ----------------------------------------------------------------------------
resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 512m
    memory: 1Gi

# ----------------------------------------------------------------------------
# CONFIGMAP
# ----------------------------------------------------------------------------
configMap:
  enabled: true
  name:

# ----------------------------------------------------------------------------
# APPLICATION CONFIGURATION
# ---------------------------------------------------------
# DATABASE CONFIGURATION
# MySQL RDS Database Endpoint and credentials will be injected via ConfigMap and Secrets
# --------------------------------------------------------
app:
  persistence:
    provider: mysql
    database: catalogdb
    secret:
      name: catalog-db

database:
  endpoint: production-catalog-mysql.cifguuuaskpf.us-east-1.rds.amazonaws.com
  port: 3306
  serviceName: catalog-mysql

# ----------------------------------------------------------------------------
# AWS SECRETS MANAGER / CSI DRIVER
# ----------------------------------------------------------------------------
secrets:
  awsRegion: us-east-1
  secretName: production/catalog/database
  secretProviderClass: catalog-db-secrets

# ----------------------------------------------------------------------------
# AUTOSCALING - HORIZONTAL POD AUTOSCALER (HPA
# ----------------------------------------------------------------------------
autoscaling:
  enabled: true

  apiVersion: argoproj.io/v1alpha1
  kind: Rollout

  minReplicas: 2
  maxReplicas: 12

  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80


# ----------------------------------------------------------------------------
# KARPENTER NODE SELECTION
# ----------------------------------------------------------------------------
# Schedule pods on Karpenter On-Demand nodes for stability
nodeSelector: {}

affinity: {}

tolerations: []

# ----------------------------------------------------------------------------
# TOPOLOGY SPREAD CONSTRAINTS
# ----------------------------------------------------------------------------
# Distribute pods across nodes AND availability zones for high availability
topologySpreadConstraints:
  enabled: true

  node:
    maxSkew: 1
    whenUnsatisfiable: ScheduleAnyway

  zone:
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule

# ----------------------------------------------------------------------------
# POD DISRUPTION BUDGET (PDB) 
# ----------------------------------------------------------------------------
# Maintain minimum availability during voluntary disruptions (node drains, etc.)
podDisruptionBudget:
  enabled: false # set to true to enable Pod Disruption Budget. If enabled, it will ensure that at least 2 pods are always available during voluntary disruptions (like node drains).
  minAvailable: 2 # At least 2 pods must remain available


# ----------------------------------------------------------------------------
# PROMETHEUS SCRAPING
# ----------------------------------------------------------------------------
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"


# ----------------------------------------------------------------------------
# OPENTELEMETRY INSTRUMENTATION
# ----------------------------------------------------------------------------
opentelemetry:
  enabled: true

  injectAnnotation: inject-java

  instrumentation:
    name: observability/retail-auto-instrumentation

  sdk:
    disabled: false
    endpoint: http://retail-traces-collector.observability:4318
    protocol: http/protobuf
    serviceName: catalog
