apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
{{ include "catalog.labels" . | nindent 4 }}

spec:

{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0

      steps:
        - setWeight: 25
        - pause: {}

        - setWeight: 50
        - pause: {}

        - setWeight: 75
        - pause:
            duration: 60s

  selector:
    matchLabels:
{{ include "catalog.selectorLabels" . | nindent 6 }}

  template:

    metadata:

      annotations:

        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

{{- with .Values.podAnnotations }}
{{ toYaml . | nindent 8 }}
{{- end }}

      labels:
{{ include "catalog.selectorLabels" . | nindent 8 }}

    spec:

      serviceAccountName: {{ include "catalog.serviceAccountName" . }}

      terminationGracePeriodSeconds: 30

      securityContext:
{{ toYaml .Values.podSecurityContext | nindent 8 }}

{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}

{{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:

        - maxSkew: {{ .Values.topologySpreadConstraints.node.maxSkew }}
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.node.whenUnsatisfiable }}

          labelSelector:
            matchLabels:
{{ include "catalog.selectorLabels" . | nindent 14 }}

        - maxSkew: {{ .Values.topologySpreadConstraints.zone.maxSkew }}
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.zone.whenUnsatisfiable }}

          labelSelector:
            matchLabels:
{{ include "catalog.selectorLabels" . | nindent 14 }}

{{- end }}

{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}

      containers:

        - name: {{ include "catalog.fullname" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:

            - configMapRef:
                name: {{ include "catalog.configMapName" . }}

            - secretRef:
                name: {{ .Values.app.persistence.secret.name }}
          
          env:
            - name: OTEL_SDK_DISABLED
              value: "{{ ternary "true" "false" .Values.opentelemetry.sdk.disabled }}"

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.opentelemetry.sdk.endpoint }}"

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "{{ .Values.opentelemetry.sdk.protocol }}"

            - name: OTEL_SERVICE_NAME
              value: "{{ .Values.opentelemetry.sdk.serviceName }}"

            - name: OTEL_TRACES_EXPORTER
              value: "otlp"

            - name: OTEL_METRICS_EXPORTER
              value: "none"

            - name: OTEL_LOGS_EXPORTER
              value: "none"
          securityContext:
{{ toYaml .Values.securityContext | nindent 12 }}

          ports:

            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.containerPort }}

            failureThreshold: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:
{{ toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true  

      volumes:

        - name: tmp-volume
          emptyDir:
            medium: Memory

        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.secrets.secretProviderClass }}"